### ISSUE TITLE
onelog is slower than zerolog actually.

### ISSUE THREAD

**Issue by phuslu** [muir/logbench#1]
It lacks/misses timestamp formatting and introduce more allocations, also onelog does not support encode struct, see
1. https://github.com/muir/logbench/commit/63f6fb10db1ca6a528e44b19102b40446e91f5e6#commitcomment-80952032
2. https://go.dev/play/p/BC4G3Ji41EY
3. https://github.com/rs/zerolog/issues/59#issuecomment-387486782
4. https://github.com/muir/logbench/commit/63f6fb10db1ca6a528e44b19102b40446e91f5e6#comments

So I added onelog to my readme benchmark to show that.

https://github.com/phuslu/log/commit/8ff11210cf69e770869f5dbab42986e440e77ccf

**Comment by phuslu** [comment]
Frankly speaking, I don't think there's another golang logger can be quick in phuslog level.

**Comment by muir** [comment]
> Frankly speaking, I don't think there's another golang logger can be quick in phuslog level.

I don't expect anyone to try.   For Xop, it needs to be fast enough that speed isn't a concern.   I'm building the features I think are important: logs in the context of traces as a unified system that's easy to use.

**Comment by phuslu** [comment]
thanks for kindly explain!
